# Generated by Django 2.0 on 2018-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0002_auto_20180108_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='media/images/product/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(null=True, upload_to='media/images/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Please enter "-" \n Note: Slug is gonna be Product Name separated by "-"', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(help_text='Please enter "-" \n Note: Slug is gonna be Category Name separated by "-"', max_length=100),
        ),
    ]
