# Generated by Django 2.0 on 2018-01-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0003_auto_20180108_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='Product Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='saleprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
