# Generated by Django 2.0 on 2018-01-10 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0005_auto_20180110_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
