# Generated by Django 2.0 on 2018-01-10 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0006_product_package_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_qty',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
