# Generated by Django 2.0 on 2018-01-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0007_auto_20180110_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, default='', upload_to='media/images/category/'),
            preserve_default=False,
        ),
    ]
